dubbo:
  registry:
    address: nacos://172.28.1.20:8848?username=nacos&password=nacos
    register-mode: instance
  protocol:
    name: tri
    port: 50052
  application:
    name: authService
    logger: slf4j
    serialization:
      # 关闭严格检查
      check-status: DISABLE
spring:
  datasource:
    url: jdbc:mysql://rm-bp146f71y348k5qjf.mysql.rds.aliyuncs.com/authservice?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 3!14atom0618
    driver-class-name: com.mysql.cj.jdbc.Driver
    jpa:
      hibernate:
        ddl-auto=update:
    data:
      redis:
        host: r-bp1nivyt3h2hkgnckb.redis.rds.aliyuncs.com
        port: 6379
        password: Offerlink123!
        database: 0
        jedis:
          pool:
            max-active: 8   # 最大连接数
            max-idle: 8     # 最大空闲连接
            min-idle: 0     # 最小空闲连接
            max-wait: 5000ms  # 等待超时时间（-1表示无限）